### ISSUE TITLE
Crash upon reaching Main Menu

### ISSUE THREAD

**Issue by MTSyntho** [Cvolton/betterinfo-geode#20] opened 2024-02-21 04:53 UTC
I am running Geode Android32 on the latest nightly as of 21 Feb 2024.
After some testing, i found out the latest ver. of BetterInfo has been crashing Geometry Dash. Before I can reach the main menu, it just craahes. All mods work as other intended.

**Comment by MTSyntho** [comment] 2024-02-24 13:29
> would you be able to share a crash log?

unsure which one is the crash log so here's 3 files i found
[launcher_logcat.txt](https://github.com/Cvolton/betterinfo-geode/files/14392992/launcher_logcat.txt)
[Crash 2024-02-24 15.25.43.dmp](https://github.com/Cvolton/betterinfo-geode/files/14392996/Crash.2024-02-24.15.25.43.dmp)
[Geode 2024-02-24 15.25.43.log](https://github.com/Cvolton/betterinfo-geode/files/14392998/Geode.2024-02-24.15.25.43.log)

**Comment by Cvolton** [comment] 2024-03-04 00:21
apologies for the late response, this appears to be an android only crash caused by a corrupted cache file - you can delete `save/geode/mods/cvolton.betterinfo/cache.json` to fix this for now. I'll make sure to add better handling of this error in the next update

**Comment by Cvolton** [comment] 2024-03-07 13:55
should be fixed in 1704dd0b8021c1d43c4e1c0b056700f8fac09cdd , update out soon

**Closed** 2024-03-16 02:01 UTC
Labels: bug
