### ISSUE TITLE
GeometryDash.exe + 23593a crashes

### ISSUE THREAD

**Issue by xparadoxical** [Cvolton/betterinfo-geode#34] opened 2024-05-01 01:07 UTC
It should be BI I think. The latest crash occured when opening Saved Levels, not sure in which of the "modes". No clue if that's how to repro it.
[8x offset 23593a.zip](https://github.com/Cvolton/betterinfo-geode/files/15172556/8x.offset.23593a.zip)

**Comment by Cvolton** [comment] 2024-05-14 16:26
hard to tell what exactly causes this, this looks like it's encountering an invalid level pointer while loading the page - BI in the crash log then could purely be a coincidence, but it could also be caused by saved level filtering in theory (which the crash log doesn't actually directly point towards but it is still a possibility regardless). Do you know if you had any saved filters enabled while this happened?

**Comment by xparadoxical** [comment] 2024-05-14 18:33
I don't think I had, I don't use them. It could as well be geode or geometry dash instead, of course

**Comment by Cvolton** [comment] 2024-09-28 09:00
closing this as it doesn't appear that any similar issue has resurfaced in 2.206

**Closed by Cvolton** 2024-09-28 09:00 UTC
