### ISSUE TITLE
Uncompleted levels show up in completed filter

### ISSUE THREAD

**Issue by Novrix** [Cvolton/betterinfo-geode#56] opened 2024-10-20 18:20 UTC
I don't know if this is intentional or not, but I've seen in the past couple weeks or so levels I've only completed in practice show up in my completed filter. It's really annoying and I believe it to be a bug as it only started happening a couple weeks ago. If it is intentional, are you able to make it optional since I don't want levels I haven't completed to show up in my completed filter?

**Comment by Cvolton** [comment] 2024-12-27 23:13
issue was the completed mode being set to "percentage" and percentage range being set to 0-100

while we stumbled onto another possible quirk of what specific levels that option gave (the search was limited to levels completed in practice?), i've been unable to reproduce any issues with it myself and these levels still fall within the intended displayed level set, so i'm closing this

**Closed by Cvolton** 2024-12-27 23:13 UTC
